plugins {
    id 'com.android.application'
}

android {
    namespace 'ir.chobyar.sketch'
    compileSdk 35
    ndkVersion '27.0.12077973'

    def ciVersionCode = System.getenv('CHOBYAR_VERSION_CODE') ?: '1'
    def ciVersionName = System.getenv('CHOBYAR_VERSION_NAME') ?: '0.0.1'

    defaultConfig {
        applicationId 'ir.chobyar.sketch'
        minSdk 26
        targetSdk 35
        versionCode ciVersionCode.toInteger()
        versionName ciVersionName

        ndk {
            abiFilters 'arm64-v8a', 'armeabi-v7a', 'x86_64'
        }

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++17'
                arguments '-DANDROID_STL=c++_shared'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }

    signingConfigs {
        chobyarDev {
            storeFile file('../chobyar-dev.jks')
            storePassword 'ChobYarDev123'
            keyAlias 'chobyar'
            keyPassword 'ChobYarDev123'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.chobyarDev
        }
        release {
            signingConfig signingConfigs.chobyarDev
            minifyEnabled false
        }
    }
}

dependencies {
    implementation 'com.google.android.filament:filament-android:1.74.0'
    implementation 'com.google.android.filament:filamat-android:1.74.0'
}
