package ir.chobyar.sketch;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Color;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.PointF;
import android.graphics.RectF;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;

import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.File;
import java.io.FileOutputStream;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * End-to-end furniture reference exercise.
 *
 * The model is built with the same SolidCSG bodies and rendered by the same
 * Shapr3DGuideCadCanvasView used by the production workspace. The drawing sheet
 * is deliberately generated by the validation harness: the production app does
 * not yet expose an automatic orthographic drawing workspace.
 */
@RunWith(AndroidJUnit4.class)
public final class FurnitureReferenceInstrumentationTest {
    private static final int VIEW_W = 1200;
    private static final int VIEW_H = 1000;

    private static final float WIDTH = 500f;
    private static final float DEPTH = 420f;
    private static final float TOTAL_HEIGHT = 480f;
    private static final float PLINTH_HEIGHT = 28f;
    private static final float BODY_HEIGHT = TOTAL_HEIGHT - PLINTH_HEIGHT;
    private static final float PANEL = 18f;
    private static final float OUTER_RADIUS = 48f;
    private static final float FRONT_WIDTH = 462f;
    private static final float FRONT_HEIGHT = 201f;
    private static final float FRONT_RADIUS = 26f;
    private static final float FRONT_GAP = 6f;

    private static final class FurnitureCanvas extends Shapr3DGuideCadCanvasView {
        FurnitureCanvas(Context context) { super(context); }
        void add(String name, SolidCSG csg) { addIndependentBody(name, csg); }
        void overview() { showModelOverview(); }
        void presentationStyle() {
            try {
                Paint fill = (Paint) privateField(SolidCadCanvasView.class, "bodyFill").get(this);
                Paint wire = (Paint) privateField(SolidCadCanvasView.class, "bodyWire").get(this);
                Paint selected = (Paint) privateField(SolidCadCanvasView.class, "selectedWire").get(this);
                fill.setColor(Color.rgb(224, 225, 207));
                wire.setColor(Color.argb(115, 54, 71, 89));
                wire.setStrokeWidth(1.25f);
                selected.setStrokeWidth(1.25f);
            } catch (Exception e) {
                throw new AssertionError(e);
            }
        }
        void frontFacingIsoCamera() {
            try {
                Field yaw = privateField(SpatialCadCanvasView.class, "cameraYaw");
                Field pitch = privateField(SpatialCadCanvasView.class, "cameraPitch");
                // The cabinet front lies at negative Y. Turn the ISO camera
                // around the vertical axis while retaining a positive pitch so
                // the result is both front-facing and viewed from above.
                yaw.setFloat(this, 218f);
                pitch.setFloat(this, 24f);
            } catch (Exception e) {
                throw new AssertionError(e);
            }
        }
        void clearBodySelection() {
            try {
                Field f = SolidCadCanvasView.class.getDeclaredField("selectedBody");
                f.setAccessible(true);
                f.set(this, null);
            } catch (Exception e) {
                throw new AssertionError(e);
            }
        }
        private static Field privateField(Class<?> owner, String name) throws Exception {
            Field f = owner.getDeclaredField(name);
            f.setAccessible(true);
            return f;
        }
    }

    @Test
    public void rendersReferenceNightstandAndDimensionedPlan() throws Exception {
        Context context = InstrumentationRegistry.getInstrumentation().getTargetContext();
        File output = new File(context.getExternalFilesDir(null), "furniture-validation");
        assertTrue(output.exists() || output.mkdirs());

        final FurnitureCanvas[] holder = new FurnitureCanvas[1];
        InstrumentationRegistry.getInstrumentation().runOnMainSync(() -> {
            FurnitureCanvas view = new FurnitureCanvas(context);
            view.measure(
                    android.view.View.MeasureSpec.makeMeasureSpec(VIEW_W, android.view.View.MeasureSpec.EXACTLY),
                    android.view.View.MeasureSpec.makeMeasureSpec(VIEW_H, android.view.View.MeasureSpec.EXACTLY));
            view.layout(0, 0, VIEW_W, VIEW_H);
            holder[0] = view;
        });

        FurnitureCanvas view = holder[0];
        InstrumentationRegistry.getInstrumentation().runOnMainSync(() -> {
            view.presentationStyle();
            buildNightstand(view, false);
            view.overview();
            view.setStandardView("FRONT");
            view.fitAll();
            view.clearBodySelection();
            captureView(view, new File(output, "01-nightstand-front-closed.png"));

            view.setStandardView("ISO");
            view.frontFacingIsoCamera();
            view.fitAll();
            captureView(view, new File(output, "02-nightstand-iso-closed.png"));

            view.clearAll();
            buildNightstand(view, true);
            view.overview();
            view.setStandardView("ISO");
            view.frontFacingIsoCamera();
            view.fitAll();
            view.clearBodySelection();
            captureView(view, new File(output, "03-nightstand-iso-open.png"));
        });

        drawTechnicalSheet(new File(output, "04-nightstand-dimensioned-plan.png"));
        writeNotes(new File(output, "05-model-specifications.txt"));

        assertEquals(5, output.listFiles() == null ? 0 : output.listFiles().length);
        for (File f : output.listFiles()) {
            long minimum = f.getName().endsWith(".png") ? 1000L : 100L;
            assertTrue(f.getName(), f.length() > minimum);
        }
    }

    private static void buildNightstand(FurnitureCanvas view, boolean open) {
        SolidCSG outer = roundedPrismXZ(0f, PLINTH_HEIGHT + BODY_HEIGHT / 2f,
                WIDTH, BODY_HEIGHT, OUTER_RADIUS, 0f, DEPTH);
        SolidCSG cavity = roundedPrismXZ(0f, PLINTH_HEIGHT + BODY_HEIGHT / 2f,
                WIDTH - 2f * PANEL, BODY_HEIGHT - 2f * PANEL, 30f,
                -1f, DEPTH - PANEL + 1f);
        view.add("پوسته اصلی 18mm", outer.subtract(cavity));

        view.add("پایه عقب نشسته", roundedPrismXZ(0f, PLINTH_HEIGHT / 2f,
                390f, PLINTH_HEIGHT, 10f, 62f, 318f));

        float lowerZ = PLINTH_HEIGHT + PANEL + FRONT_HEIGHT / 2f;
        float upperZ = lowerZ + FRONT_HEIGHT + FRONT_GAP;
        float upperPull = open ? -118f : -12f;
        float lowerPull = open ? -228f : -12f;
        addDrawer(view, "کشوی بالا", upperZ, upperPull, open);
        addDrawer(view, "کشوی پایین", lowerZ, lowerPull, open);

        // A shallow centered finger lip, matching the reference seam detail.
        view.add("لبه دستگیره", roundedPrismXZ(0f,
                lowerZ + FRONT_HEIGHT / 2f + 1f,
                112f, 9f, 4.5f, lowerPull - 7f, 8f));
    }

    private static void addDrawer(FurnitureCanvas view, String name,
                                  float centerZ, float frontY, boolean open) {
        view.add(name + " • نما", roundedPrismXZ(0f, centerZ,
                FRONT_WIDTH, FRONT_HEIGHT, FRONT_RADIUS, frontY, 28f));
        if (!open) return;

        float boxStart = frontY + 24f;
        float boxDepth = 350f;
        float boxBottomZ = centerZ - FRONT_HEIGHT / 2f + 17f;
        float sideHeight = FRONT_HEIGHT - 42f;
        float sideCenterZ = boxBottomZ + sideHeight / 2f;

        view.add(name + " • کف", roundedPrismXZ(0f, boxBottomZ,
                FRONT_WIDTH - 34f, 18f, 2f, boxStart, boxDepth));
        view.add(name + " • بغل چپ", roundedPrismXZ(-FRONT_WIDTH / 2f + 26f,
                sideCenterZ, 18f, sideHeight, 3f, boxStart, boxDepth));
        view.add(name + " • بغل راست", roundedPrismXZ(FRONT_WIDTH / 2f - 26f,
                sideCenterZ, 18f, sideHeight, 3f, boxStart, boxDepth));
        view.add(name + " • پشت", roundedPrismXZ(0f, sideCenterZ,
                FRONT_WIDTH - 52f, sideHeight, 5f,
                boxStart + boxDepth - 18f, 18f));
    }

    private static SolidCSG roundedPrismXZ(float cx, float cz,
                                            float width, float height, float radius,
                                            float yStart, float depth) {
        Geometry3D.Plane3D xzAtY = new Geometry3D.Plane3D(
                new Geometry3D.Vec3(0f, yStart, 0f),
                new Geometry3D.Vec3(1f, 0f, 0f),
                new Geometry3D.Vec3(0f, 0f, 1f),
                "XZ");
        return SolidCSG.extrude(roundedRect(cx, cz, width, height, radius), xzAtY, -depth);
    }

    private static List<PointF> roundedRect(float cx, float cy,
                                             float width, float height, float radius) {
        float hw = width / 2f;
        float hh = height / 2f;
        float r = Math.max(0f, Math.min(radius, Math.min(hw, hh)));
        if (r < 0.01f) {
            List<PointF> rect = new ArrayList<>();
            rect.add(new PointF(cx - hw, cy - hh));
            rect.add(new PointF(cx + hw, cy - hh));
            rect.add(new PointF(cx + hw, cy + hh));
            rect.add(new PointF(cx - hw, cy + hh));
            return rect;
        }
        List<PointF> points = new ArrayList<>();
        addArc(points, cx + hw - r, cy - hh + r, r, -90f, 0f);
        addArc(points, cx + hw - r, cy + hh - r, r, 0f, 90f);
        addArc(points, cx - hw + r, cy + hh - r, r, 90f, 180f);
        addArc(points, cx - hw + r, cy - hh + r, r, 180f, 270f);
        return points;
    }

    private static void addArc(List<PointF> points, float cx, float cy,
                               float radius, float startDeg, float endDeg) {
        int segments = 8;
        for (int i = 0; i <= segments; i++) {
            double angle = Math.toRadians(startDeg + (endDeg - startDeg) * i / segments);
            points.add(new PointF(cx + radius * (float) Math.cos(angle),
                    cy + radius * (float) Math.sin(angle)));
        }
    }

    private static void captureView(FurnitureCanvas view, File file) {
        Bitmap bitmap = Bitmap.createBitmap(VIEW_W, VIEW_H, Bitmap.Config.ARGB_8888);
        Canvas canvas = new Canvas(bitmap);
        canvas.drawColor(Color.rgb(247, 246, 242));
        view.draw(canvas);
        save(bitmap, file);
    }

    private static void drawTechnicalSheet(File file) {
        int width = 1800;
        int height = 1500;
        Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
        Canvas c = new Canvas(bitmap);
        c.drawColor(Color.WHITE);

        Paint ink = paint(Color.rgb(28, 42, 58), 5f, Paint.Style.STROKE);
        Paint fine = paint(Color.rgb(80, 96, 112), 2.5f, Paint.Style.STROKE);
        Paint dim = paint(Color.rgb(35, 112, 205), 2.5f, Paint.Style.STROKE);
        Paint title = textPaint(46f, Paint.Align.LEFT, Color.rgb(20, 35, 50));
        Paint label = textPaint(30f, Paint.Align.CENTER, Color.rgb(20, 35, 50));
        Paint note = textPaint(25f, Paint.Align.LEFT, Color.rgb(65, 78, 92));

        c.drawText("ChobYar 3D • Two-drawer nightstand • mm", 70f, 75f, title);
        c.drawText("Reference-derived proportions — verify final dimensions before manufacturing", 70f, 116f, note);

        float s = 1.08f;
        float fx = 95f, fy = 665f;
        drawRoundedRect(c, fx, fy, WIDTH * s, BODY_HEIGHT * s, OUTER_RADIUS * s, ink);
        c.drawLine(fx, fy - (PLINTH_HEIGHT + PANEL + FRONT_HEIGHT + FRONT_GAP) * s,
                fx + WIDTH * s, fy - (PLINTH_HEIGHT + PANEL + FRONT_HEIGHT + FRONT_GAP) * s, fine);
        float seamY = fy - (PLINTH_HEIGHT + PANEL + FRONT_HEIGHT + FRONT_GAP / 2f) * s;
        c.drawLine(fx + 20f, seamY, fx + WIDTH * s - 20f, seamY, fine);
        RectF plinth = new RectF(fx + 55f, fy, fx + WIDTH * s - 55f, fy + PLINTH_HEIGHT * s);
        c.drawRoundRect(plinth, 8f, 8f, ink);
        c.drawText("FRONT", fx + WIDTH * s / 2f, fy + 78f, label);
        dimensionH(c, fx, fx + WIDTH * s, fy + 132f, "500", dim, label);
        dimensionV(c, fx - 55f, fy - BODY_HEIGHT * s, fy + PLINTH_HEIGHT * s, "480", dim, label);

        float sx = 850f, sy = 665f;
        drawRoundedRect(c, sx, sy, DEPTH * s, BODY_HEIGHT * s, 38f, ink);
        RectF sidePlinth = new RectF(sx + 65f, sy, sx + DEPTH * s - 35f, sy + PLINTH_HEIGHT * s);
        c.drawRoundRect(sidePlinth, 8f, 8f, ink);
        c.drawText("RIGHT", sx + DEPTH * s / 2f, sy + 78f, label);
        dimensionH(c, sx, sx + DEPTH * s, sy + 132f, "420", dim, label);

        float tx = 95f, ty = 950f;
        RectF top = new RectF(tx, ty, tx + WIDTH * s, ty + DEPTH * s);
        c.drawRoundRect(top, OUTER_RADIUS * s, OUTER_RADIUS * s, ink);
        c.drawText("TOP", tx + WIDTH * s / 2f, ty + DEPTH * s + 58f, label);
        dimensionH(c, tx, tx + WIDTH * s, ty - 45f, "500", dim, label);
        dimensionV(c, tx - 55f, ty, ty + DEPTH * s, "420", dim, label);

        float bx = 850f, by = 950f;
        Paint box = paint(Color.rgb(225, 231, 236), 1f, Paint.Style.FILL);
        c.drawRoundRect(new RectF(bx, by, 1700f, 1440f), 24f, 24f, box);
        c.drawText("MODEL SPECIFICATION", bx + 30f, by + 50f, note);
        c.drawText("Overall: 500 W × 420 D × 480 H", bx + 30f, by + 95f, note);
        c.drawText("Carcass / drawer panels: 18 mm", bx + 30f, by + 140f, note);
        c.drawText("Outer radius: R48 • drawer fronts: R26", bx + 30f, by + 185f, note);
        c.drawText("Front gap: 6 mm • recessed plinth: 390 × 318 × 28", bx + 30f, by + 230f, note);
        c.drawText("Open test: upper travel 106 • lower travel 216", bx + 30f, by + 275f, note);

        save(bitmap, file);
    }

    private static void drawRoundedRect(Canvas c, float left, float bottom,
                                        float width, float height, float radius, Paint p) {
        c.drawRoundRect(new RectF(left, bottom - height, left + width, bottom), radius, radius, p);
    }

    private static void dimensionH(Canvas c, float x1, float x2, float y,
                                   String text, Paint line, Paint label) {
        c.drawLine(x1, y, x2, y, line);
        arrow(c, x1, y, 1f, 0f, line);
        arrow(c, x2, y, -1f, 0f, line);
        c.drawText(text + " mm", (x1 + x2) / 2f, y - 12f, label);
    }

    private static void dimensionV(Canvas c, float x, float y1, float y2,
                                   String text, Paint line, Paint label) {
        c.drawLine(x, y1, x, y2, line);
        arrow(c, x, y1, 0f, 1f, line);
        arrow(c, x, y2, 0f, -1f, line);
        c.save();
        c.rotate(-90f, x - 12f, (y1 + y2) / 2f);
        c.drawText(text + " mm", x - 12f, (y1 + y2) / 2f, label);
        c.restore();
    }

    private static void arrow(Canvas c, float x, float y, float dx, float dy, Paint p) {
        float px = -dy, py = dx;
        Path path = new Path();
        path.moveTo(x, y);
        path.lineTo(x + dx * 16f + px * 7f, y + dy * 16f + py * 7f);
        path.moveTo(x, y);
        path.lineTo(x + dx * 16f - px * 7f, y + dy * 16f - py * 7f);
        c.drawPath(path, p);
    }

    private static Paint paint(int color, float stroke, Paint.Style style) {
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        p.setColor(color);
        p.setStrokeWidth(stroke);
        p.setStyle(style);
        return p;
    }

    private static Paint textPaint(float size, Paint.Align align, int color) {
        Paint p = new Paint(Paint.ANTI_ALIAS_FLAG);
        p.setColor(color);
        p.setTextSize(size);
        p.setTextAlign(align);
        return p;
    }

    private static void save(Bitmap bitmap, File file) {
        try (FileOutputStream out = new FileOutputStream(file)) {
            assertTrue(bitmap.compress(Bitmap.CompressFormat.PNG, 100, out));
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }

    private static void writeNotes(File file) {
        String text = String.format(Locale.US,
                "ChobYar furniture reference validation\n" +
                "Overall: %.0f x %.0f x %.0f mm (W x D x H)\n" +
                "Panel: %.0f mm\nOuter radius: R%.0f mm\n" +
                "Drawer front: %.0f x %.0f mm, R%.0f, gap %.0f mm\n" +
                "Plinth: 390 x 318 x 28 mm\n" +
                "Assumption: proportions inferred from two reference photos; no scale was supplied.\n",
                WIDTH, DEPTH, TOTAL_HEIGHT, PANEL, OUTER_RADIUS,
                FRONT_WIDTH, FRONT_HEIGHT, FRONT_RADIUS, FRONT_GAP);
        try (FileOutputStream out = new FileOutputStream(file)) {
            out.write(text.getBytes(java.nio.charset.StandardCharsets.UTF_8));
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }
}
