package ir.chobyar.sketch;

import androidx.test.core.app.ApplicationProvider;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import org.junit.Test;
import org.junit.runner.RunWith;
import ir.chobyar.sketch.core.ConstructionPlane;
import ir.chobyar.sketch.core.ConstructionPlaneDocument;
import static org.junit.Assert.*;

/** Production contracts for plane-aware Sketch placement and construction Items. */
@RunWith(AndroidJUnit4.class)
public final class ProfessionalSketchPlacementInstrumentationTest {
    private static K33MirroredCadCanvasView canvas(){return new K33MirroredCadCanvasView(ApplicationProvider.getApplicationContext());}
    private static void onMain(Runnable task){final Throwable[] failure={null};InstrumentationRegistry.getInstrumentation().runOnMainSync(()->{try{task.run();}catch(Throwable t){failure[0]=t;}});if(failure[0] instanceof AssertionError)throw(AssertionError)failure[0];if(failure[0] instanceof RuntimeException)throw(RuntimeException)failure[0];if(failure[0]!=null)throw new RuntimeException(failure[0]);}

    @Test public void constructOffsetCreatesPlaneWithoutSketch(){onMain(()->{K33MirroredCadCanvasView cad=canvas();cad.setStandardView("ISO");String before=cad.activeSketchStableId();String plane=cad.createOffsetConstructionPlane(12.5f,"Shelf datum");assertTrue(cad.hasConstructionPlane(plane));assertEquals(before,cad.activeSketchStableId());assertEquals(12.5,cad.constructionPlaneOffsetMm(plane),0.0);assertTrue(cad.is3DOverview());});}
    @Test public void constructBasePlanesExistWithoutCreatingSketch(){onMain(()->{K33MirroredCadCanvasView cad=canvas();String before=cad.activeSketchStableId();ProfessionalSketchPlacementController p=new ProfessionalSketchPlacementController(cad);assertTrue(p.typedItemIds().contains("PLANE:"+ConstructionPlane.XY_ID));assertTrue(p.typedItemIds().contains("PLANE:"+ConstructionPlane.XZ_ID));assertTrue(p.typedItemIds().contains("PLANE:"+ConstructionPlane.YZ_ID));assertEquals(before,cad.activeSketchStableId());});}
    @Test public void sketchFromModelRequiresExplicitTargetAndCancelCreatesNothing(){onMain(()->{K33MirroredCadCanvasView cad=canvas();cad.setStandardView("ISO");ProfessionalSketchPlacementController p=new ProfessionalSketchPlacementController(cad);String before=cad.activeSketchStableId();long revision=cad.constructionPlaneModelRevision();assertTrue(p.begin());assertEquals(ProfessionalSketchPlacementController.State.AWAITING_TARGET,p.state());assertEquals(before,cad.activeSketchStableId());assertEquals(revision,cad.constructionPlaneModelRevision());p.cancel();assertEquals(ProfessionalSketchPlacementController.State.INACTIVE,p.state());assertEquals(before,cad.activeSketchStableId());assertEquals(revision,cad.constructionPlaneModelRevision());});}
    @Test public void sketchOnBuiltInAndOffsetPlaneReferenceExactStableIds(){onMain(()->{K33MirroredCadCanvasView cad=canvas();cad.setStandardView("ISO");ProfessionalSketchPlacementController p=new ProfessionalSketchPlacementController(cad);assertTrue(p.begin());String first=p.startNewSketchOnPlane(ConstructionPlane.XY_ID);assertEquals(ConstructionPlane.XY_ID,p.planeIdForSketch(first));cad.setStandardView("ISO");String offset=cad.createOffsetConstructionPlane(18f,"Door datum");assertTrue(p.begin());String second=p.startNewSketchOnPlane(offset);assertEquals(offset,p.planeIdForSketch(second));assertNotEquals(first,second);});}
    @Test public void planeItemsAreTypedAndModelOwned(){onMain(()->{K33MirroredCadCanvasView cad=canvas();ProfessionalSketchPlacementController p=new ProfessionalSketchPlacementController(cad);String offset=cad.createOffsetConstructionPlane(7f,"Shelf datum");assertTrue(p.typedItemIds().contains("PLANE:"+offset));long revision=cad.constructionPlaneModelRevision();assertTrue(cad.setConstructionPlaneVisibility(offset,false));assertFalse(cad.isConstructionPlaneVisible(offset));assertTrue(cad.constructionPlaneModelRevision()>revision);assertTrue(p.renamePlane(offset,"Shelf datum renamed"));assertEquals(offset,p.planeIdByDisplayName("Shelf datum renamed"));assertEquals(ConstructionPlaneDocument.DeleteResult.BUILT_IN,p.deletePlane(ConstructionPlane.XY_ID));});}
    @Test public void referencedAndDerivedPlanesFailClosedOnDelete(){onMain(()->{K33MirroredCadCanvasView cad=canvas();ProfessionalSketchPlacementController p=new ProfessionalSketchPlacementController(cad);String parent=cad.createOffsetConstructionPlane(10f,"Parent");String child=cad.createOffsetConstructionPlane(5f,"Child");assertEquals(ConstructionPlaneDocument.DeleteResult.HAS_DERIVED_PLANES,p.deletePlane(parent));cad.setStandardView("ISO");assertTrue(p.begin());p.startNewSketchOnPlane(child);assertEquals(ConstructionPlaneDocument.DeleteResult.IN_USE,p.deletePlane(child));});}
}